Added searching with name date and person
eXtgmA/vacation_rental pull request #63
Opened 2023-12-17 19:29 UTC by BBuermann-IT

Now its possible to search for unbooked houses by given filtervalues

2023-12-17 19:29 UTC, eXtgmA commented
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...acation_rental/src/controller/OfferController.php  1      0
..._rental/vacation_rental/src/views/search.view.php  9      0
----------------------------------------------------------------------
A TOTAL OF 10 ERRORS WERE FIXED IN 2 FILES
----------------------------------------------------------------------

Time: 2.21 secs; Memory: 12MB

```

2023-12-17 19:38 UTC, eXtgmA commented
# Autofix Result
Fix code style issues automatically
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...ation_rental/vacation_rental/src/models/House.php  1      0
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 2.36 secs; Memory: 12MB

```

2023-12-17 20:28 UTC, ReneSansSerif commented on src/views/search.view.php
> +/**
Für diesen Job gibt es schon die Helperfunktion "prefill", welche über den Header eingebunden ist.
Du kannst sie einfach mit dem variablennamen aufrufen den du bei der Zuweisung im Array  "old_POST" benutzt hast.
ZB  <?php prefill("destination") ?>

2023-12-17 20:31 UTC, ReneSansSerif requested changes
Den Progress in OfferController.php in Funktion postEdit() bitte nicht löschen. Das wird noch gebraucht

2023-12-17 20:31 UTC, ReneSansSerif commented on src/controller/OfferController.php
> -
Alle folgend gelöschten Zeilen bitte nicht löschen. Das ist Progress der verloren gehen würde.

2023-12-18 11:15 UTC, ReneSansSerif approved these changes
Hab die gelöschten Zeilen wieder reingerollbacked,
Kann jetzt gemerged weren.

2023-12-18 11:16 UTC, merged